### ISSUE TITLE
AWS Signature Version 4 support

### ISSUE THREAD

**Issue by vosmik** [akappen/s3_direct_upload#1]
Hi, thanks for the library.
Maybe I am doing something wrong, but when I want to upload a picture to S3 I get:

<Error>
  <Code>InvalidRequest</Code>
  <Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message>
</Error>

I think it' because of Signature Version. I am uploading it to EU-central(Frankfurkt) bucket which uses only Signature Version 4, but US West (formerly US standard) still supports Signature Version 2 too. Is the library built on top of Version 2? Do you consider adding Version 4 support? 

http://docs.aws.amazon.com/general/latest/gr/sigv4_changes.html

Edited: I tried uploading to US-west bucket and it just works. So I think the problem is really the Signature Version.

**Comment by snewcomer** [comment]
I'm wondering the same thing.  Is this something we can help with?

**Comment by jxxcarlson** [comment]
I am also having trouble with this -- am using Version 4 as you mentioned above, e.g., 
 the following credential: "AK../20170812T124615Z/us-east-1/s3/aws4_request".  

I need rather urgently to get my file uploader working, so one possibility would be to work on some code to get it working and submit a pull request.  I am rather a noob at this, but I've been reading the docs and think that it is doable. 

What say you all?  I am more than happy to defer to someone with more experience.

**Comment by akappen** [comment]
I will take a look at supporting Signature Version 4 soon. In the meantime pull requests are welcome.

Thanks for the report!

**Comment by jxxcarlson** [comment]
Looking forward to this!

**Comment by akappen** [comment]
I just updated the library to use AWS Signature V4. I tested it out on in a production application on a bucket located in the `us-east-1` region and it worked great. Hopefully it will work in all regions now.

The only external change is that you can optionally configure the AWS region that your bucket is located in, this is described in the hex docs and the README on github.

Cheers!

**Comment by akappen** [comment]
Fixed in version 0.1.3
