### ISSUE TITLE
Review Request

### ISSUE THREAD

**Issue by psteininger** [akappen/s3_direct_upload#4]
@akappen  I made a fork of this repo and did some rework to use ExAws for source of Credentials (Access ID and Access Secret). I plan on releasing it over the weekend, as a package with a slightly different name, and hopefully eventually get it under the ex-aws org. I wanted to give you an opportunity to look over the code and make sure I am not violating the Apache 2.0 License. I left an attribution in the copyright line of the license.  I do want to give you a proper credit for the work you have done to make this functionality work.

Please let me know your thoughts. If I don't hear from you by Monday, I will assume all is OK with you.

Here's the link: https://github.com/laborvoices/ex_aws_s3_direct_upload

Best,

Piotr

**Comment by akappen** [comment]
@psteininger 

This looks good to me. I originally wrote this library because `ExAws` didn't support this use case, so I hope you can get it adopted by the `ex-aws` org.

Cheers!

**Comment by psteininger** [comment]
Thanks @akappen, I appreciate your support. This is my first foray into releasing Elixir packages. It's great to start with someone else base :). It's a bummer `ex_aws_s3` does not have the presigned POST JSON, only presigned_url, which causes a lot of issues with replacing the file's content (i.e. you can't rename it). 

I hope `ex-aws` will either accept the transfer of the package or someone will take the time to fold it into `ex_aws_s3`
